version: '3'

services:
  container:
    build: ./container-todo
    ports:
      - "8080:8080"
    depends_on:
      - mfe-app-todo-create
      - mfe-app-todo-list

  mfe-app-todo-create:
    build: ./mfe-app-todo-create
    ports:
      - "8081:8081"

  mfe-app-todo-list:
    build: ./mfe-app-todo-list
    ports:
      - "8082:8082"
